### ISSUE TITLE
user name TextInputEditText maxLine not working

### ISSUE THREAD

**Issue by bu2zhouzhu** [zpauly/GitHub_Android#4]
Line 42 of activity_login.xml.

Quote from [this](http://stackoverflow.com/questions/7092961/edittext-maxlines-not-working-user-can-still-input-more-lines-than-set#answer-7094141) answer:
> The attribute `maxLines` corresponds to the maximum height of the `EditText`, it controls the outer boundaries and not inner text lines.

You can simply use `android:singleLine` which is deprecated in API 3 or write a "row limiter" like [this](http://stackoverflow.com/questions/7092961/edittext-maxlines-not-working-user-can-still-input-more-lines-than-set#answer-7103931).

**Comment by zpauly** [comment]
Think you for your advice,I'll take it.
